### ISSUE TITLE
Automation won't buy max

### ISSUE THREAD

**Issue by 1e1000000** [TheTastyPi/Exponential-Madness#20]
![image](https://user-images.githubusercontent.com/54700438/74414040-91a9f500-4e7b-11ea-849e-613f7d670a46.png)
Look cost and number

**Comment by TheTastyPi** [comment]
This is intentional. If this wasn't implemented, it would only buy the first multiplier due to what I can only assume is precision errors.

**Comment by F1e308** [comment]
But all cost is eee9.16e30 and have eee9.92e30
